from __future__ import annotations

import types
from typing import Any


def _emit(message: str) -> None:
    try:
        import diagnostics
        diagnostics._emit(message)
    except Exception:
        pass


def install(services: Any) -> None:
    """Map profile progress and install post-runtime service controls."""
    import customtkinter as ctk

    original_root_init = ctk.CTk.__init__

    def root_init(self: Any, *args: Any, **kwargs: Any) -> None:
        original_root_init(self, *args, **kwargs)

        def patch_app() -> None:
            if not hasattr(self, "_set_progress") or not hasattr(self, "_append_log"):
                try:
                    self.after(100, patch_app)
                except Exception:
                    pass
                return
            if getattr(self, "_jarnsen_profile_progress_ui", False):
                return
            self._jarnsen_profile_progress_ui = True

            def profile_progress(fraction: float, stage: str, detail: str = "") -> None:
                fraction = max(0.0, min(1.0, float(fraction)))
                # The original workflow uses 79% for profile restore and moves to
                # name/reboot stages afterwards. Keep those later milestones intact.
                overall = 0.79 + 0.07 * fraction
                suffix = f" · {detail}" if detail else ""
                self._set_progress(overall, f"{stage}{suffix}")

            services._jarnsen_profile_progress_callback = profile_progress
            _emit("PROFILE PROGRESS UI installed overall-range=0.79..0.86")

        try:
            self.after(320, patch_app)
        except Exception:
            pass

    ctk.CTk.__init__ = root_init

    # flash_runtime has already installed the staged profile restore before this
    # layer is loaded. Wrap that restore so Meshtastic special admin messages are
    # sent outside the settings transaction; this fixes the observed 49/49 stall.
    from profile_specials_fix import install as install_profile_specials_fix
    install_profile_specials_fix(services)

    # These UI layers must be imported from a normal, non-generated module so
    # PyInstaller discovers and bundles them. _build_version.py is regenerated by
    # the workflow and therefore must not be used as a runtime-hook location.
    from firmware_only import install as install_firmware_only
    install_firmware_only(services)

    from usb_log_download import install as install_usb_log_download
    install_usb_log_download(services)

    from profile_editor import install as install_profile_editor
    install_profile_editor(services)

    from dashboard_cleanup import install as install_dashboard_cleanup
    install_dashboard_cleanup(services)

    _emit(
        "PROFILE PROGRESS UI layer installed + firmware-only + usb-log + "
        "profile-specials-fix + profile-editor + dashboard-cleanup"
    )
